version: '3.8'

services:
  next-crud:
    build:
      context: .
      target: development
      dockerfile: ./docker/next.Dockerfile
    ports:
      - 3000:3000
    command: yarn dev
    container_name: next-crud
    restart: unless-stopped
    networks:
      - crud-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

networks:
  crud-network: